CREATED = "{} created successfully."
DELETED = "{} deleted successfully."
ERROR_404 = "{} with {} '{}' was not found."
ERROR_404_LIST = "No {} found."
MEMBER_LOGOUT = "User logged out successfully."
MEMBER_400 = "User is not logged in."
MODIFIED = "{} modified successfully."
